- name: Setup Apache on web server
  hosts: lampweb
  become: yes

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Create document root
      file:
        path: /var/www/html
        state: directory

    - name: Start Apache
      service:
        name: httpd
        state: started
        enabled: yes
